apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Применение одной командой:  kubectl apply -k deploy/golden
resources:
  - 00-namespaces.yaml
  - 10-serviceaccounts.yaml
  - 20-workloads.yaml
  - 30-services.yaml
  - 40-peer-authentication.yaml
  - 50-authorization-policies.yaml
