apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Применение одной командой:  kubectl apply -k deploy/golden
resources:
  - istio-demo.yaml
  - 00-namespaces.yaml
  - 10-serviceaccounts.yaml
  - 20-workloads.yaml
  - 30-services.yaml
  - 40-peer-auth.yaml
  - 50-auth-policies.yaml
