apiVersion: v1
kind: Service
metadata:
  name: acgd
  namespace: acg-system
  labels:
    app.kubernetes.io/name: acgd
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: acgd
  ports:
    - name: http
      port: 8080
      targetPort: 8080
